### ISSUE TITLE
Stable version manifests not included

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/generate-manifest-list#1]

**Comment by Mark-Simulacrum** [comment]
channel-rust-stable.toml is in the list; do you actually need the 1.x manifests?

**Comment by emilyalbini** [comment]
I'd just list all files that match `channel-*.toml`.

**Comment by jethrogb** [comment]
> channel-rust-stable.toml is in the list

Oh I see. I was indeed using the 1.x manifests before.

**Comment by Mark-Simulacrum** [comment]
I intentionally avoided the "list all" when implementing since it seemed off somehow to me, but I would be willing to implement just finding all manifest files as @pietroalbini suggests.

**Comment by Mark-Simulacrum** [comment]
Fixed in 81f3ad4218f5aa03d9f1dd8f34051147173c4cf6, and included on static-r-l.o.
