### ISSUE TITLE
Tool crashes when trying to fetch the manifest metadata

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/generate-manifest-list#2]
The tool tries to guess the date of the inventory we need to look at, but it's currently off by 4 hours. We should implement a more resilient way to discover the latest manifest, for example by listing the available dates in the inventory directory.

**Comment by jethrogb** [comment]
Triage: the index is now over a year out of date

**Comment by Mark-Simulacrum** [comment]
We now use the list API to get the timestamp right, so this should also be fixed. Closing.

(https://static.rust-lang.org/manifests.txt is up to date as of today).
